DATA SEGMENT
    A DB ? ; PEREMENNAYA DLYA HRANENIYA ZNACHENIYA A
    X DB ? ; PEREMENNAYA DLYA HRANENIYA ZNACHENIYA X
    Y DB ? ; PEREMENNAYA DLYA HRANENIYA ZNACHENIYA Y
    PERENOS DB 13,10,"$" ; SIMVOLY PEREVODA STROKI (CRLF) I SIMVOL KONCA STROKI DLYA DOS
    VVOD_A DB 13,10,"VVEDITE A=$" ; SOOBSHCHENIE PRIGLASHENIYA DLYA VVODA A, OKANCHIVAYUSHCHEESYA SIMVOLOM KONCA STROKI
    VVOD_X DB 13,10,"VVEDITE X=$",13,10 ; SOOBSHCHENIE PRIGLASHENIYA DLYA VVODA X, OKANCHIVAYUSHCHEESYA SIMVOLOM KONCA STROKI
    VIVOD_Y DB "Y=$" ; SOOBSHCHENIE DLYA VYVODA ZNACHENIYA Y
ENDS   

STACK SEGMENT
    DW 128 DUP(0) ; OPREDELENIE STEKA RAZMEROM 128 SLOV, INICIALIZIRUETSYA NULYAMI
ENDS    

CODE SEGMENT
START:
; USTANOVKA SEGMENTNYH REGISTROV:
MOV AX, DATA ; ZAGRUZKA SEGMENTA DANNYH V AX
MOV DS, AX ; USTANOVKA SEGMENTA DANNYH
MOV ES, AX ; USTANOVKA DOPOLNITEL'NOGO SEGMENTA
XOR AX, AX ; OBNULENIE REGISTRA AX
MOV DX, OFFSET VVOD_A ; ZAGRUZKA ADRESA STROKI PRIGLASHENIYA DLYA VVODA A V DX
MOV AH, 9 ; USTANOVKA FUNKCII DOS DLYA VYVODA STROKI
INT 21H ; VYZOV DOS DLYA VYVODA STROKI

SLED2:
    MOV AH, 1 ; USTANOVKA FUNKCII DOS DLYA VVODA SIMVOLA S KLAVIATURY
    INT 21H ; VYZOV DOS
    CMP AL, "-" ; PROVERKA, YAVLYAETSYA LI VVEDENNYJ SIMVOL ZNAKOM MINUSA
    JNZ SLED1 ; PEREKHOD, ESLI VVEDENNYJ SIMVOL NE MINUS
    MOV BX, 1 ; USTANOVKA PRIZNAKA MINUSA
    JMP SLED2 ; POVTORNYJ VVOD SIMVOLA  

SLED1:
    SUB AL, 30H ; PREOBRAZOVANIE ASCII KODA CIFRY V CHISLOVOE ZNACHENIE
    TEST BX, BX ; PROVERKA PRIZNAKA MINUSA
    JZ SLED3 ; PEREKHOD, ESLI PRIZNAK MINUSA NE USTANOVLEN
    NEG AL ; INVERSIYA ZNAKA CHISLA

SLED3:
    MOV A, AL ; SOHRANENIE ZNACHENIYA A
    XOR AX, AX ; OBNULENIE REGISTRA AX
    XOR BX, BX ; OBNULENIE REGISTRA BX
    MOV DX, OFFSET VVOD_X ; ZAGRUZKA ADRESA STROKI PRIGLASHENIYA DLYA VVODA X V DX
    MOV AH, 9 ; USTANOVKA FUNKCII DOS DLYA VYVODA STROKI
    INT 21H ; VYZOV DOS DLYA VYVODA STROKI 

SLED4:
    MOV AH, 1 ; USTANOVKA FUNKCII DOS DLYA VVODA SIMVOLA S KLAVIATURY
    INT 21H ; VYZOV DOS
    CMP AL, "-" ; PROVERKA, YAVLYAETSYA LI VVEDENNYJ SIMVOL ZNAKOM MINUSA
    JNZ SLED5 ; PEREKHOD, ESLI VVEDENNYJ SIMVOL NE MINUS
    MOV BX, 1 ; USTANOVKA PRIZNAKA MINUSA
    JMP SLED4 ; POVTORNYJ VVOD SIMVOLA 

SLED5:
    SUB AL, 30H ; PREOBRAZOVANIE ASCII KODA CIFRY V CHISLOVOE ZNACHENIE
    TEST BX, BX ; PROVERKA PRIZNAKA MINUSA
    JZ SLED6 ; PEREKHOD, ESLI PRIZNAK MINUSA NE USTANOVLEN
    NEG AL ; INVERSIYA ZNAKA CHISLA 
    
SLED6:
    MOV X, AL ; SOHRANENIE ZNACHENIYA X  
    MOV AX, 0
    MOV AL, X ; ZAGRUZKA ZNACHENIYA A V AL
    CMP AL, 0 ; SRAVNENIE ZNACHENIJ X I 0
    JZ @RIGHT ; PEREKHOD, ESLI A = 0
    MOV AL, A
    IDIV X
    MOV DL, AL
    MOV AL, X 
    JMP @Y1
@RIGHT:
    MOV DL, 9 ; PRISVAIVANEY Y2 = 9, ESLI X != 0
    MOV AL, X 
    JMP @Y1

@MODUL: ;NAHODIT MODUL CHISLA
    NEG AL 
    JMP @Y1
    
@Y1:  
    MOV AH, 0
    CMP AL, 0
    JL @MODUL ;ESLI X < 0, NAHODIM MODUL
    CMP AL, 4
    JA @RES     
    MOV CL, 4
    ADD CL, A 
    JMP @VIXOD
     
@RES:    
    MOV AX, 0
    MOV AL, 2
    MUL X
    MOV CL, AL
   

@VIXOD: 
    MOV AX, 0
    MOV AL, CL
    ADD AL, DL ; Y1 + Y2
    
    MOV Y, AL ; SOHRANENIE REZUL'TATA V Y
    MOV DX, OFFSET PERENOS ; ZAGRUZKA ADRESA STROKI PEREVODA STROKI V DX
    MOV AH, 9 ; USTANOVKA FUNKCII DOS DLYA VYVODA STROKI
    INT 21H ; VYZOV DOS DLYA VYVODA STROKI
    MOV DX, OFFSET VIVOD_Y ; ZAGRUZKA ADRESA STROKI "Y=" V DX
    MOV AH, 9 ; USTANOVKA FUNKCII DOS DLYA VYVODA STROKI
    INT 21H ; VYZOV DOS DLYA VYVODA STROKI
    MOV AL, Y ; ZAGRUZKA ZNACHENIYA Y V AL
    CMP Y, 0 ; PROVERKA ZNAKA Y
    JGE SLED7 ; PEREKHOD, ESLI Y >= 0
    NEG AL ; INVERSIYA ZNAKA, ESLI Y < 0
    MOV BL, AL ; SOHRANENIE POLOZHITEL'NOGO ZNACHENIYA V BL
    MOV DL, "-" ; ZAGRUZKA ZNAKA MINUSA V DL
    MOV AH, 2 ; USTANOVKA FUNKCII DOS DLYA VYVODA SIMVOLA
    INT 21H ; VYZOV DOS DLYA VYVODA SIMVOLA
    MOV DL, BL ; ZAGRUZKA POLOZHITEL'NOGO ZNACHENIYA V DL
    ADD DL, 30H ; PREOBRAZOVANIE ZNACHENIYA V ASCII KOD
    INT 21H ; VYZOV DOS DLYA VYVODA SIMVOLA
    JMP SLED8 ; PEREKHOD K ZAVERSHENIYU
  
SLED7:
    MOV DL, Y ; ZAGRUZKA ZNACHENIYA Y V DL
    ADD DL, 30H ; PREOBRAZOVANIE ZNACHENIYA V ASCII KOD
    MOV AH, 2 ; USTANOVKA FUNKCII DOS DLYA VYVODA SIMVOLA
    INT 21H ; VYZOV DOS DLYA VYVODA SIMVOLA
SLED8:
    MOV DX, OFFSET PERENOS ; ZAGRUZKA ADRESA STROKI PEREVODA STROKI V DX
    MOV AH, 9 ; USTANOVKA FUNKCII DOS DLYA VYVODA STROKI
    INT 21H ; VYZOV DOS DLYA VYVODA STROKI
    
    MOV AH, 1 ; USTANOVKA FUNKCII DOS DLYA OZHIDANIYA NAZHATIYA KLAVISHI
    INT 21H ; VYZOV DOS DLYA OZHIDANIYA NAZHATIYA KLAVISHI
    MOV AX, 4C00H ; USTANOVKA FUNKCII DOS DLYA VYHODA IZ PROGRAMMY
    INT 21H ; VYZOV DOS DLYA ZAVERSHENIYA PROGRAMMY
ENDS
END START ; USTANOVKA TOCHKI VHODA I ZAVERSHENIE ASSEMBLIROVANIYA
